default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: password

production:
  <<: *default
  database: <%= ENV.fetch('TOASTY_PROD_DB') %>
  username: <%= ENV.fetch('TOASTY_PROD_USER') %>
  password: <%= ENV.fetch('TOASTY_PROD_PASSWORD') %>

development:
  <<: *default
  database: toasty_server_development

test:
  <<: *default
  database: toasty_server_test
