default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: toasty_server_development

test:
  <<: *default
  database: toasty_server_test
